import { AppProps } from "next/dist/shared/lib/router/router";
import Head from 'next/head';
import React, { Fragment } from "react";
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <Fragment>
      <Head>
        <title>My top - the best top</title>
        <meta name="description" content="Generated by create next app #2" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="crossOrigin" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </Head>
 
      <Component {...pageProps} />
    </Fragment>
  );
}

export default MyApp;
